agntcy/slim

- .github/CODEOWNERS
Using the github team as CODEOWNERS is easier to manage.
> chore: use agp-maintainers team as codeowners

- .github/workflows/reusable-python-build-wheels.yaml
- data-plane/python-bindings/README.md
Allow linux arm64 users to install the wheel without rebuild it (which requires the rust toolchain stalled).
> feat(python-wheels): add aarch64 build

- data-plane/Cargo.lock
- data-plane/examples/Cargo.toml
- data-plane/gateway/config/CHANGELOG.md
- data-plane/gateway/config/Cargo.toml
- data-plane/gateway/gateway/CHANGELOG.md
- data-plane/gateway/gateway/Cargo.toml
- data-plane/gateway/nop_component/Cargo.toml
- data-plane/gateway/service/CHANGELOG.md
- data-plane/gateway/service/Cargo.toml
- data-plane/gateway/tracing/CHANGELOG.md
- data-plane/gateway/tracing/Cargo.toml
- data-plane/python-bindings/Cargo.toml
* `agp-tracing`: 0.1.0 -> 0.1.1 (✓ API compatible changes)
* `agp-gw`: 0.2.0 -> 0.2.1 (✓ API compatible changes)
* `agp-service`: 0.1.0 -> 0.1.1 (✓ API compatible changes)
* `agp-config`: 0.1.0 -> 0.1.1
<blockquote>
- implement opentelemetry tracing subscriber
</blockquote>
<blockquote>
- implement opentelemetry tracing subscriber
</blockquote>
<blockquote>
- implement opentelemetry tracing subscriber
</blockquote>
<blockquote>
- updated the following local packages: agp-tracing
</blockquote>
</p></details>
---
> chore: release

- .github/workflows/release-images.yaml
When multiple tags are pushed at once, they need to all match the regex that triggers the workflow.
Set the regex to `agp-*` to allow matching all tags.
> fix(release-image): trigger workflow for any tag starting with agp-*

- data-plane/gateway/gateway/build.rs
- data-plane/gateway/gateway/src/args.rs
- data-plane/gateway/gateway/src/bin/main.rs
- data-plane/gateway/gateway/src/build_info.rs
The current gateway main executable does not provide any info about version and build environment.
Add the `--version` flag. This can be used in the following way:
```bash
gateway --version
Version:        agp-gw-v0.2.0-1-g53676b0
Build Date:     2025-02-12T18:08:56Z
Git SHA:        53676b0
Profile:        debug
```
> feat: add build info to main gateway executable

- data-plane/python-bindings/Taskfile.yml
- data-plane/python-bindings/uv.lock
- data-plane/rust-tooling/toolchain.yml
When building the bindings from the Taskfile in data-plane,
the build profile and target are not propagated by default to the 
"python-bindings:packaging" target.
> fix(python-bindings): propagate build PROFILE up to "python-bindings:packaging"  task target

- .github/workflows/release-images.yaml
Remove targets for check gw image release
> fix: remove target for bake list to check image release

- data-plane/Cargo.lock
- data-plane/gateway/datapath/Cargo.toml
- data-plane/gateway/datapath/benches/pool_benchmark.rs
- data-plane/gateway/datapath/src/tables/pool.rs
The goal was to measure the performance of the connection pool, and address the potential performance issues.
Baseline performance test:
```
pool insert             time:   [334.62 µs 335.07 µs 335.63 µs]
Found 6 outliers among 100 measurements (6.00%)
1 (1.00%) high mild
5 (5.00%) high severe
pool lookup             time:   [1.0598 µs 1.0604 µs 1.0610 µs]
Found 12 outliers among 100 measurements (12.00%)
5 (5.00%) high mild
7 (7.00%) high severe
pool grow               time:   [336.44 µs 337.22 µs 338.02 µs]
Found 4 outliers among 100 measurements (4.00%)
4 (4.00%) high mild
pool capacity           time:   [898.70 ns 899.33 ns 900.28 ns]
Found 5 outliers among 100 measurements (5.00%)
2 (2.00%) high mild
3 (3.00%) high severe 
```
It turned out that the machine level code for …
> perf: improve connection pool performance

- data-plane/Cargo.lock
- data-plane/examples/src/sdk-mock/main.rs
- data-plane/gateway/datapath/src/forwarder.rs
- data-plane/gateway/datapath/src/message_processing.rs
- data-plane/gateway/datapath/src/messages/encoder.rs
- data-plane/gateway/datapath/src/messages/utils.rs
- data-plane/gateway/datapath/src/tables/subscription_table.rs
- data-plane/gateway/service/Cargo.toml
- data-plane/gateway/service/src/errors.rs
- data-plane/gateway/service/src/fire_and_forget.rs
- data-plane/gateway/service/src/lib.rs
- data-plane/gateway/service/src/request_response.rs
- data-plane/gateway/service/src/session.rs
- data-plane/gateway/service/src/session_layer.rs
- data-plane/gateway/service/src/timer.rs
- data-plane/python-bindings/agp_bindings/__init__.py
- data-plane/python-bindings/agp_bindings/_agp_bindings.pyi
- data-plane/python-bindings/src/lib.rs
- data-plane/python-bindings/tests/test_bindings.py
- data-plane/testing/src/bin/publisher.rs
- data-plane/testing/src/bin/subscriber.rs
- data-plane/testing/src/bin/workload-gen.rs
Request/Response session type.
This is a first draft and requires extensive testing. Unit tests will be added in a second PR.
Introduce the Request/Response session type:
- in a request/reply session, if a reply is not received before the timeout, an error is returned to the application
- application can now receive either messages or errors: an example of an error is a timeout on a request for which a reply was not received before the timeout
- multiple messages can be sent in parallel - multiple timers will be set, one for each request
- for each timeout that triggers, an error is sent to the application
> feat: request/reply session type

- data-plane/Cargo.lock
Upgrade `aws-lc-rs` and `aws-lc-sys` respectively to version `1.13.0` and `0.28.0` to address this error [happening in CI](https://github.com/agntcy/agp/actions/runs/14199960570/job/39784251140): 
```
c11.c
C:\Program Files\Microsoft Visual
Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\include\vcruntime_c11_stdatomic.h(16):
fatal error C1189: #error:  "C atomics require C11 or later"
cargo:warning=Compilation of 'c11.c' failed
```
> fix: windows error when compiling aws-lc-rs

- .github/workflows/reusable-python-build-wheels.yaml
- data-plane/python-bindings/README.md
By building the bindings on ubuntu 24.04 we force a glibc version that is quite recent and does not
work on old systems. Switch to ubuntu 22.04 to use 2.35
> fix(agp-bindings): build pypi package on ubuntu 22.04

- .github/workflows/control-plane.yaml
```
[Invalid workflow file: .github/workflows/control-plane.yaml#L19](https://github.com/agntcy/agp/actions/runs/14837620684/workflow)
The workflow is not valid. .github/workflows/control-plane.yaml (Line: 19, Col: 23): Unexpected symbol: ')'.
```
> ci: fix workflow file

- data-plane/integrations/mcp/mcp-proxy/CHANGELOG.md
- data-plane/integrations/mcp/mcp-proxy/Cargo.lock
- data-plane/integrations/mcp/mcp-proxy/Cargo.toml
* `agp-mcp-proxy`: 0.1.0 -> 0.1.1
<blockquote>
- release mcp proxy ([#206](https://github.com/agntcy/agp/pull/206))
- release mcp proxy ([#204](https://github.com/agntcy/agp/pull/204))
</blockquote>
</p></details>
---
> release agp-mcp-proxy-v0.1.1

- data-plane/integrations/mcp/mcp-proxy/CHANGELOG.md
- data-plane/integrations/mcp/mcp-proxy/Cargo.lock
- data-plane/integrations/mcp/mcp-proxy/Cargo.toml
* `agp-mcp-proxy`: 0.1.1 -> 0.1.2
<blockquote>
- release mcp-proxy docker image ([#210](https://github.com/agntcy/agp/pull/210))
</blockquote>
</p></details>
---
> release: agp-mcp-proxy-v0.1.2

- data-plane/integrations/mcp/mcp-proxy/CHANGELOG.md
- data-plane/integrations/mcp/mcp-proxy/Cargo.lock
- data-plane/integrations/mcp/mcp-proxy/Cargo.toml
* `agp-mcp-proxy`: 0.1.2 -> 0.1.3
<blockquote>
- add sse transport to the mcp-server-time example ([#234](https://github.com/agntcy/agp/pull/234))
- detect client disconnection in mcp proxy ([#208](https://github.com/agntcy/agp/pull/208))
- add integration test suite ([#233](https://github.com/agntcy/agp/pull/233))
</blockquote>
</p></details>
---
> release agp-mcp-proxy-v0.1.3

- data-plane/integrations/mcp/mcp-proxy/CHANGELOG.md
- data-plane/integrations/mcp/mcp-proxy/Cargo.lock
- data-plane/integrations/mcp/mcp-proxy/Cargo.toml
* `agp-mcp-proxy`: 0.1.3 -> 0.1.4
<blockquote>
- properly close agp-mcp proxy ([#261](https://github.com/agntcy/agp/pull/261))
</blockquote>
</p></details>
---
> release agp-mcp-proxy-v0.1.4

- data-plane/python-bindings/Taskfile.yml
- data-plane/python-bindings/WINDOWS.md
Lint deps groups are not required when building
the python wheels.
> fix(python-bindings): do not install lint dependencies when building wheels

- .github/actions/trigger-integrations/action.yaml
- .github/workflows/release-helm.yaml
- .github/workflows/release-images.yaml
Fix csit integration test trigger action
> fix(ci): use buildbot token for trigger integration tests in csit

- data-plane/gateway/datapath/src/errors.rs
- data-plane/gateway/datapath/src/message_processing.rs
- data-plane/python-bindings/uv.lock
Reconnection loop currently does not handle termination signal.
This PR fixes it by processing the reconnection loop together with
the signals.
> fix(data-path): reconnection loop

- data-plane/integrations/mcp/agp-mcp/packages/agp-mcp/pyproject.toml
- data-plane/integrations/mcp/agp-mcp/packages/agp-mcp/src/agp_mcp/client.py
- data-plane/integrations/mcp/agp-mcp/uv.lock
- data-plane/integrations/mcp/mcp-proxy/Cargo.toml
Force sticky sessions for agp-mcp, so that the client will
always reach out to the same server during the same session.
> feat(agp-mcp): use sticky sessions

- .github/release-config.json
- .github/release-manifest.json
- data-plane/testing/Dockerfile
- data-plane/testing/Taskfile.yml
- docker-bake.hcl
Create a container image containing publisher, subscriber and workload-gen commands which are test utils for gateway testing.
> feat: add intial testutil image build

- data-plane/testing/Dockerfile
- tasks/rust.yaml
This will enforce the use of LLVM as opposed to GCC
for c components like aws-lc.
> fix(testing-apps): build using common rust taskfiles

- data-plane/integrations/mcp/mcp-proxy/CHANGELOG.md
- data-plane/integrations/mcp/mcp-proxy/Cargo.lock
- data-plane/integrations/mcp/mcp-proxy/Cargo.toml
* `agntcy-slim-mcp-proxy`: 0.1.4 -> 0.1.5
<blockquote>
- remove agntcy- prefix from mcp-proxy release ([#301](https://github.com/agntcy/agp/pull/301))
</blockquote>
</p></details>
---
> release agntcy-slim-mcp-proxy-v0.1.5

- .github/actions/trigger-integrations/action.yaml
The CSIT repository integration workflow inputs default are changed to explicitly include the tests instead of explicitly exclude those. This change is helpful to avoid future problems, where can be more tests and this way does not need every dependent repository to update the remote trigger call.
https://github.com/agntcy/csit/pull/122
- [] New code contribution is covered by automated tests
> fix: update CSIT remote workflow call inputs after default changes

- data-plane/core/controller/src/service.rs
- data-plane/core/datapath/proto/v1/pubsub.proto
- data-plane/core/datapath/src/api.rs
- data-plane/core/datapath/src/api/gen/pubsub.proto.v1.rs
- data-plane/core/datapath/src/message_processing.rs
- data-plane/core/datapath/src/messages/utils.rs
- data-plane/core/datapath/tests/data_path_test.rs
- data-plane/core/service/src/app.rs
- data-plane/core/service/src/channel_endpoint.rs
- data-plane/core/service/src/fire_and_forget.rs
- data-plane/core/service/src/interceptor.rs
- data-plane/core/service/src/interceptor_mls.rs
- data-plane/core/service/src/lib.rs
- data-plane/core/service/src/producer_buffer.rs
- data-plane/core/service/src/receiver_buffer.rs
- data-plane/core/service/src/request_response.rs
- data-plane/core/service/src/session.rs
- data-plane/core/service/src/streaming.rs
- data-plane/core/service/src/testutils.rs
- data-plane/integrations/mcp/mcp-proxy/src/proxy.rs
Introduce the concept of `SessionType` in the session header of messages.
This is required as now we have message types that can be shared across
different sessions (like MLS ones). This will allow to understand the SessionType
for these kind of messages as well.
> feat(proto): introduce SessionType in message header

- data-plane/testing/Cargo.toml
- data-plane/testing/README.md
This PR fixes issue #390 by adding the missing `channel` binary configuration to the testing workspace's `Cargo.toml` file. The `channel.rs` binary was present in `src/bin/` and referenced in `Taskfile.yml` but was missing from the `Cargo.toml` binary definitions, making it unbuildable with `cargo run --bin channel`.
**Changes made:**
- Added `[[bin]]` section for `channel` binary in `data-plane/testing/Cargo.toml`
- Updated `data-plane/testing/README.md` to document the channel binary usage and options
**Testing:**
- Verified the channel binary builds successfully with `cargo check --bin channel`
- All existing binaries remain functional
Fixes: #390
> fix: add missing channel binary to testing Cargo.toml

- data-plane/core/service/src/streaming.rs
Fix MLS update timer duration (move from 10sec to 1 hour) in streaming session
> fix: mls update timer duration

- control-plane/Taskfile.yaml
- control-plane/control-plane/internal/config/config.go
Fix config field name mapping to fix the problem of config.yaml is not loaded by Control Plane on startup.
> fix: control plane config is not loaded

- .github/workflows/reusable-helm-release.yaml
Keep the "v" in front of helm chart versions when releasing.
> ci: fix version format in helm charts

- charts/slim/Chart.yaml
- charts/slim/templates/configmap.yaml
- charts/slim/templates/service.yaml
- charts/slim/values.yaml
Add slim.overrideConfig property to values file, to have a possibility to override the whole default SLIM service config.
> fix: add slim.overrideConfig to helm values

- data-plane/python-bindings/slima2a/README.md
- data-plane/python-bindings/slima2a/examples/echo_agent/client.py
- data-plane/python-bindings/slima2a/slima2a/handler.py
- data-plane/python-bindings/slima2a/slima2a/types/a2a_pb2_srpc.py
- data-plane/python-bindings/srpc/srpc/__init__.py
- data-plane/python-bindings/srpc/srpc/channel.py
- data-plane/python-bindings/srpc/srpc/common.py
- data-plane/python-bindings/srpc/srpc/examples/simple/client.py
- data-plane/python-bindings/srpc/srpc/examples/simple/server.py
- data-plane/python-bindings/srpc/srpc/examples/simple/types/example_pb2_srpc.py
- data-plane/python-bindings/srpc/srpc/rpc.py
- data-plane/python-bindings/srpc/srpc/server.py
[refactor(srpc): prefix private channel methods with underscore](https://github.com/agntcy/slim/commit/5434b5af40744fc8123bb2d9e99f6807fa646ad0)
[refactor(srpc): Cleanup and mypy fixes](https://github.com/agntcy/slim/commit/aaa5fa1bc69abaf6839ddde182c9e2c777179991)
[refactor(srpc,slima2a): Rename ErrorResponse to SRPCResponseError](https://github.com/agntcy/slim/commit/da2282cef68685dfc47b3f3f29330c7ccf8ba679)
> refactor(srpc): prefix private channel methods with underscore

- data-plane/integrations/mcp/mcp-proxy/Cargo.lock
- data-plane/integrations/mcp/mcp-proxy/Taskfile.yaml
This PR fixes the missing task reference in the mcp-proxy Taskfile.
Currently, the mcp-proxy:test task depends on multiple subtasks defined in rust.yaml. However, bindings:test is present in the mcp-proxy Taskfile, while core:test is missing. As a result, running mcp-proxy:test fails with a missing task error (mcp-proxy:core:test).
Changes in this PR:
Added the missing core:test task to the mcp-proxy Taskfile dependencies.
Ensured that mcp-proxy:test runs successfully without errors.
Why this is needed:
Without this fix, the mcp-proxy:test task cannot be executed, which blocks test execution and CI workflows that rely on it.
> task: add missing task in mcp-proxy Taskfile

- data-plane/Cargo.lock
- data-plane/config/base/client-config.yaml
- data-plane/config/proxy/client-config.yaml
- data-plane/core/config/Cargo.toml
- data-plane/core/config/src/grpc.rs
- data-plane/core/config/src/grpc/client.rs
- data-plane/core/config/src/grpc/errors.rs
- data-plane/core/config/src/grpc/proxy.rs
- data-plane/integrations/mcp/mcp-proxy/Cargo.lock
Add support for HTTP proxy, allowing connection
among SLIM instances with a HTTP proxy in between.
HTTPs proxy support will come in a future PR.
> feat(grpc): add support for HTTP proxy

- .github/workflows/data-plane-coverage.yaml
- README.md
- tasks/rust.yaml
Adds a GitHub Action to run Rust coverage with the Taskfile and upload results to Codecov. Uses cargo llvm-cov and the lcov.info output. Closes #649 if merged.
> ci: publish Rust coverage to Codecov using Taskfile

- charts/slim/Chart.yaml
- charts/slim/templates/daemonset.yaml
- charts/slim/templates/service.yaml
- charts/slim/templates/statefulset.yaml
- charts/slim/values.yaml
- data-plane/core/config/src/component/id.rs
- data-plane/core/controller/src/service.rs
- data-plane/core/service/src/lib.rs
SLIM nodes checks for SLIM_SVC_ID_SUFFIX env var and appends to it's  ID when they register to the Controller.
Add new flag to helm deployment: slim.daemonset. If set to true there will be a SLIM node deployed to each k8s node.
In case  slim.daemonset = false (default) there will be slim.replicaCount number of SLIM nodes  deployed as StatefulSet.
In case of a Daemonset will be set to the name of the node, while in case of SatefulSet will be set with name of the pod running the node, thus SLIm nodes will register with unique ID in the cluster.
Related issue: https://github.com/agntcy/slim/issues/629
> SLIM node ID should be unique in a deployment

- data-plane/python/integrations/pyproject.toml
- data-plane/python/integrations/slima2a/examples/echo_agent/client.py
- data-plane/python/integrations/slima2a/examples/travel_planner_agent/client.py
- data-plane/python/integrations/slima2a/pyproject.toml
- data-plane/python/integrations/slimrpc/pyproject.toml
- data-plane/python/integrations/slimrpc/slimrpc/__init__.py
- data-plane/python/integrations/slimrpc/slimrpc/channel.py
- data-plane/python/integrations/slimrpc/slimrpc/examples/simple/client.py
- data-plane/python/integrations/uv.lock
This allows you to create a ChannelFactory separately from a Channel, the SLIM binding instance will belong to the ChannelFactory and only the session/connection to a particular remote will be owned by the Channel.
This prevents applications which use a lot of Channels / dynamically create channels from having to join the SLIM network many times with different unique identities, instead the Channels reuse the slim connection from the ChannelFactory.
> feat(slimrpc): separate Channel and ChannelFactory

- data-plane/python/integrations/slim-mcp/pyproject.toml
- data-plane/python/integrations/slima2a/pyproject.toml
- data-plane/python/integrations/slimrpc/pyproject.toml
- data-plane/python/integrations/slimrpc/slimrpc/rpc.py
- tasks/python.yaml
Certain packages define type annotations well even thought
they are missing the py.typed marker, in this case we can use
follow_untyped_imports to get good type checking anyway.
> chore(mypy): Be explict about ignoring untyped imports

- data-plane/core/auth/src/jwt.rs
- data-plane/core/auth/src/jwt_middleware.rs
- data-plane/core/auth/src/resolver.rs
- data-plane/core/auth/src/shared_secret.rs
- data-plane/core/controller/src/service.rs
- data-plane/core/datapath/src/message_processing.rs
- data-plane/core/datapath/src/tables/subscription_table.rs
- data-plane/core/service/src/session/channel_endpoint.rs
- data-plane/core/service/src/session/interceptor_mls.rs
- data-plane/core/service/src/session/point_to_point.rs
- data-plane/core/tracing/src/lib.rs
- data-plane/rust-toolchain.toml
Upgrade to latest rust toolchain.
> build: upgrade to rust toolchain 1.90.0

- data-plane/python/bindings/examples/src/slim_bindings_examples/README_multicast.md
- data-plane/python/bindings/examples/src/slim_bindings_examples/README_point_to_point.md
fix readmes for python bindings examples
> docs: fix readmes for python bindings examples
