CODE_OF_CONDUCT.md, SECURITY.md
=> chore: change domain to agntcy.org

data-plane/python-bindings/pyproject.toml
=> feat: add metadata for pypi

.github/workflows/release-check.yaml, .github/workflows/release-images.yaml
=> fix(release-images): do not fail if bake target do not exist

data-plane/config/base/client-config.yaml, data-plane/config/base/server-config.yaml, data-plane/config/base/server-otel-config.yaml, data-plane/examples/Taskfile.yml, data-plane/examples/src/sdk-mock/main.rs, data-plane/python-bindings/agp_bindings/__init__.py, data-plane/python-bindings/uv.lock
=> fix(examples): fix examples tests

.github/workflows/release-images.yaml
Don't try to release new images based on all the agp- tag because of the different versions
=> fix: gw image release

CODE_OF_CONDUCT.md
=> chore: update pull_request_template.md

data-plane/gateway/datapath/pubsub/proto/v1/pubsub.proto, data-plane/gateway/datapath/src/messages/encoder.rs, data-plane/gateway/datapath/src/pubsub/gen/pubsub.proto.v1.rs, data-plane/gateway/service/src/session.rs, data-plane/gateway/service/src/session_layer.rs, data-plane/gateway/service/src/streaming.rs, data-plane/testing/src/bin/publisher.rs, data-plane/testing/src/bin/subscriber.rs
- add pub/sub session layer extending the streaming implementation with bidirectional mode. 
- add pub/sub capability in rust testing app
=> feat: add pub/sub session layer

data-plane/Cargo.lock, data-plane/deny.toml, data-plane/gateway/config/Cargo.toml, data-plane/gateway/config/src/grpc/client.rs, data-plane/gateway/config/src/grpc/server.rs, data-plane/gateway/config/src/testutils/helloworld.rs, data-plane/gateway/datapath/Cargo.toml, data-plane/gateway/datapath/src/message_processing.rs, data-plane/gateway/datapath/src/pubsub/gen/pubsub.proto.v1.rs, data-plane/gateway/service/Cargo.toml, data-plane/python-bindings/uv.lock
Update to latest version of [tonic](https://docs.rs/tonic/latest/tonic/)
=> deps(data-plane): tonic 0.12.3 -> 0.13

data-plane/gateway/service/src/request_response.rs, data-plane/gateway/service/src/streaming.rs, data-plane/gateway/service/src/timer.rs
=> feat: add exponential timers

data-plane/gateway/datapath/pubsub/proto/v1/pubsub.proto, data-plane/gateway/datapath/src/messages/utils.rs, data-plane/gateway/datapath/src/pubsub/gen/pubsub.proto.v1.rs, data-plane/gateway/service/src/producer_buffer.rs, data-plane/gateway/service/src/receiver_buffer.rs, data-plane/gateway/service/src/session_layer.rs, data-plane/gateway/service/src/streaming.rs, data-plane/gateway/service/src/timer.rs
=> feat: add beacon messages at the producer

data-plane/gateway/service/src/fire_and_forget.rs, data-plane/gateway/service/src/request_response.rs, data-plane/gateway/service/src/session_layer.rs, data-plane/gateway/service/src/streaming.rs
Add tests for session deletion.
=> feat(session): add tests for session deletion

data-plane/Taskfile.yaml, tasks/rust.yaml
Create common rust taskfile to be reused across the project.
=> feat: create reusable taskfiles

integrations/mcp/agp-mcp/packages/agp-mcp/src/agp_mcp/client.py, integrations/mcp/mcp-proxy/README.md, integrations/mcp/mcp-proxy/Taskfile.yaml, integrations/mcp/mcp-proxy/examples/mcp-agp-client/README.md, integrations/mcp/mcp-proxy/examples/mcp-agp-client/main.py, integrations/mcp/mcp-proxy/examples/mcp-agp-client/pyproject.toml, integrations/mcp/mcp-proxy/examples/mcp-agp-client/uv.lock, integrations/mcp/mcp-proxy/examples/mcp-server/README.md, integrations/mcp/mcp-proxy/examples/mcp-server/main.py
- Add test for server notifications
- Add callbacks configuration at the client when using AGP transport
=> feat: test mpc notifications

.github/workflows/control-plane.yaml, Taskfile.yaml, control-plane/Taskfile.yaml, control-plane/cmd/agpctl/main.go, control-plane/internal/cmd/route/route.go, control-plane/internal/controller/client.go, control-plane/internal/controller/client_test.go
=> ci: fix control-plane CI

control-plane/agpctl/internal/cmd/route/route.go
=> fix: fix description

.github/workflows/release-agpctl.yaml
=> ci: fix release process

.github/workflows/release-agpctl.yaml, control-plane/agpctl/internal/cmd/route/route.go
=> ci: fix permissions

.github/workflows/release-python.yaml
=> fix(release-python.yaml): reusable workflow name

.github/workflows/release-python.yaml
Fix publish condition to handle skipped jobs
=> fix(release-python.yaml): fix publish condition to handle skipped jobs

data-plane/integrations/mcp/agp-mcp/examples/mcp-server-time/src/mcp_server_time/server.py, data-plane/integrations/mcp/mcp-proxy/Taskfile.yaml
=> feat: add sse transport to the mcp-server-time example

.github/workflows/data-plane.yaml, .github/workflows/integrations.yaml, data-plane/integrations/mcp/agp-mcp/examples/mcp-server-time/src/mcp_server_time/server.py, data-plane/integrations/mcp/agp-mcp/packages/agp-mcp/src/agp_mcp/common.py, data-plane/integrations/mcp/agp-mcp/packages/agp-mcp/src/agp_mcp/server.py
=> fix(agp-mcp): lint

data-plane/config/telemetry/server-config.yaml, data-plane/deny.toml, data-plane/gateway/datapath/src/message_processing.rs, data-plane/gateway/datapath/src/messages/utils.rs, data-plane/gateway/service/src/streaming.rs, data-plane/python-bindings/examples/streaming.py
=> feat: improve tracing in agp

data-plane/gateway/datapath/src/messages/encoder.rs, data-plane/gateway/datapath/src/tables.rs, data-plane/gateway/datapath/src/tables/pool.rs, data-plane/gateway/datapath/src/tables/subscription_table.rs, data-plane/gateway/datapath/tests/data_path_test.rs
Add for_each to iterate over subscription table.
=> feat(subscription_table): add foreach to iterate over the table

data-plane/gateway/gateway/Cargo.toml, data-plane/integrations/mcp/mcp-proxy/Cargo.lock, data-plane/integrations/mcp/mcp-proxy/Cargo.toml
=> fix(mcp-proxy): dependencies

data-plane/integrations/mcp/agp-mcp/packages/agp-mcp/pyproject.toml, data-plane/integrations/mcp/mcp-proxy/Cargo.lock
=> feat(agp-mcp): update to latest bindings version

.github/workflows/reusable-helm-lint-test.yaml, charts/agp/Chart.yaml, charts/agp/templates/NOTES.txt, charts/agp/templates/_helpers.tpl, charts/agp/templates/configmap.yaml, charts/agp/templates/ingress.yaml, charts/agp/templates/mcp-porxy-deployment.yaml, charts/agp/templates/mcp-proxy-configmap.yaml, charts/agp/templates/service.yaml, charts/agp/values.yaml
=> feat(chart): add MCP proxy support

data-plane/integrations/mcp/mcp-proxy/src/proxy.rs
=> fix: properly close agp-mcp proxy

data-plane/gateway/service/src/session_layer.rs
=> fix: create fnf session also on FnfReliable message

data-plane/gateway/service/src/fire_and_forget.rs, data-plane/python-bindings/uv.lock
=> fix(fire-and-forget): send the ack back to the source

.github/workflows/integration-tests.yaml, tests/integration/control_data_plane_test.go
Adding a test for listing routes.
```
[AfterSuite] PASSED [10.027 seconds]
------------------------------
Ran 1 of 1 Specs in 15.068 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
```
=> test: add integration test for listing routes

data-plane/.release-plz.toml, data-plane/Cargo.lock, data-plane/python-bindings/Cargo.toml
=> fix: release-plz tag and release names

charts/slim/Chart.yaml
Release new helm chart with slim application.
=> feat(helm): upgrade to SLIM 0.3.15

.github/release-manifest.json, charts/slim/CHANGELOG.md, charts/slim/Chart.yaml
=> chore: revert "chore(main): release slim-helm 0.1.5"

data-plane/Cargo.lock, data-plane/Cargo.toml, data-plane/core/datapath/src/message_processing.rs, data-plane/core/datapath/src/tables/subscription_table.rs, data-plane/core/service/src/fire_and_forget.rs, data-plane/rust-toolchain.toml
Upgrade to latest rust version.
=> feat(data-plane): upgrade to rust 1.87

charts/slim/templates/deployment.yaml, charts/slim/values.yaml
This PR adds extraVolumes and extraVolumemounts to the Slim deployment. This can be useful for example mounting certificates, etc...
=> feat(chart): add extra Volumes and Volumemounts to the slim deployment

data-plane/Cargo.lock, data-plane/core/auth/src/file_watcher.rs, data-plane/core/config/Cargo.toml, data-plane/core/config/src/tls/client.rs, data-plane/core/config/src/tls/common.rs, data-plane/core/config/src/tls/server.rs, data-plane/core/config/tests/tls.rs, data-plane/integrations/mcp/mcp-proxy/Cargo.lock
Signed-off-by: Mauro Sardara <msardara@cisco.com>
Support hot reload of TLS certificates.
=> feat: support hot reload of TLS certificates

data-plane/testing/Taskfile.yml, data-plane/testing/src/bin/channel.rs
=> feat: improve channel testing app

data-plane/core/service/src/app.rs
=> fix: fix building problem

control-plane/control-plane/README.md
Initial README with a simple example for Control Plane.
=> docs: add initial README for control plane

control-plane/common/proto/controlplane/v1/controlplane.pb.go, control-plane/common/proto/controlplane/v1/controlplane_grpc.pb.go, control-plane/control-plane/internal/db/db.go, control-plane/control-plane/internal/db/inmemory.go, control-plane/control-plane/internal/services/nbapiservice/groupservice.go, control-plane/control-plane/internal/services/nbapiservice/nbapiservice.go, control-plane/control-plane/internal/util/util.go, proto/controlplane/v1/controlplane.proto
Implement backend for the group service, using inmem db for now.
=> feat: group svc backend with inmem db

control-plane/Dockerfile
These variables needs to be declared for cross compilation to work.
=> fix(control-plane/Dockerfile): declare TARGETOS and TARGETARCH variables

.github/release-config.json, .github/workflows/release-helm.yaml, .github/workflows/reusable-helm-release.yaml
Release the slim-control-plane chart from the workflow
=> feat: release the chart for slim-controller

.github/workflows/reusable-helm-release.yaml
=> ci: fix version in reusable helm release

data-plane/core/service/src/session.rs, data-plane/python-bindings/examples/src/slim_bindings_examples/fire_and_forget.py, data-plane/python-bindings/slim_bindings/_slim_bindings.pyi, data-plane/python-bindings/src/pysession.rs, data-plane/python-bindings/src/utils.rs, data-plane/python-bindings/tests/test_fire_forget.py, data-plane/python-bindings/tests/test_request_reply.py
Expose source and destination name of a message in python
Ref: #487
=> feat: get source and destination name from python

charts/slim/Chart.yaml
Upgrade slim helm image to 0.4.0 version.
=> feat(slim-helm): upgrade helm to slim image 0.4.0

data-plane/python-bindings/srpc/src/srpc/context.py, data-plane/python-bindings/srpc/src/srpc/server.py
Pass request context to handlers.
=> feat(srpc): add context to handlers

data-plane/python-bindings/slima2a/examples/echo_agent/README.md, data-plane/python-bindings/slima2a/examples/echo_agent/client.py, data-plane/python-bindings/slima2a/examples/echo_agent/echo_agent.py, data-plane/python-bindings/slima2a/examples/echo_agent/echo_agent_executor.py, data-plane/python-bindings/slima2a/examples/echo_agent/server.py, data-plane/python-bindings/slima2a/pyproject.toml, data-plane/python-bindings/slima2a/slima2a/client_transport.py, data-plane/python-bindings/slima2a/slima2a/handler.py, data-plane/python-bindings/slima2a/slima2a/types/a2a_pb2_srpc.py, data-plane/python-bindings/uv.lock
Adding echo agent example to the slima2a module to be used for SRPC testing.
=> feat(py,slima2a): add example echo_agent

data-plane/python-bindings/slima2a/examples/travel_planner_agent/config.json
Added example Azure model configuration (without endpoint) for the slima2a travel planner example.
=> docs(dp,py,slima2a,travel): add example config

.github/workflows/buf-ci.yaml, buf.yaml, data-plane/core/controller/proto/v1/controller.proto, proto/buf.yaml, proto/controlplane/v1/controlplane.proto
=> feat: Update buff ci config

data-plane/python-bindings/srpc/srpc/channel.py
When errors are sent from the server with code != OK we need to decode it to "Status" instead of decoding it to the expected message structure. Once decode this can be converted to an SPRCResponseError exception and raised to be caught in the client.
=> fix(srpc): Make sure that channel handles error responses

charts/slim/values.yaml, data-plane/config/base/client-config.yaml, data-plane/config/base/server-config.yaml, data-plane/config/basic-auth/client-config.yaml, data-plane/config/basic-auth/server-config.yaml, data-plane/config/jwt-auth/ecdsa-client-config.yaml, data-plane/config/jwt-auth/ecdsa-server-config.yaml, data-plane/config/jwt-auth/hmac-client-config.yaml, data-plane/config/jwt-auth/hmac-server-config.yaml, data-plane/config/jwt-auth/rsa-client-config.yaml, data-plane/config/jwt-auth/rsa-server-config.yaml, data-plane/config/mtls/client-config.yaml, data-plane/config/mtls/server-config.yaml, data-plane/config/reference/config.yaml, data-plane/config/telemetry/server-config.yaml, data-plane/config/tls/client-config.yaml, data-plane/config/tls/server-config.yaml, data-plane/core/controller/src/config.rs, data-plane/core/service/src/lib.rs, data-plane/examples/config/docker-client-config.yaml, data-plane/integrations/mcp/mcp-proxy/Cargo.lock, data-plane/integrations/mcp/mcp-proxy/config/mcp-proxy-config.yaml, data-plane/testing/src/bin/test_ff.rs, data-plane/testing/src/bin/test_group.rs, tests/integration/testdata/client-a-config.yaml, tests/integration/testdata/client-b-config.yaml, tests/integration/testdata/server-a-config-cp.yaml, tests/integration/testdata/server-a-config.yaml, tests/integration/testdata/server-b-config-cp.yaml, tests/integration/testdata/server-b-config.yaml
Fixes : #584 
Replaced pubsub section with dataplance in the node-config.
=> feat: replace pubsub with dataplane in the node-config

.github/workflows/data-plane.yaml, .github/workflows/reusable-python-build-wheels.yaml
Fix the build of the docker images with the python examples.
=> fix(ci): python examples image build

.github/workflows/release-rust.yaml
Fix path of mcp-proxy in release-rust workflow.
=> fix(release-rust): mcp-proxy path

.github/workflows/release-python.yaml
Fix tag names in python release workflow.
=> ci: fix slimrpc and slima2a tag names

.github/workflows/integrations.yaml, .github/workflows/python-integrations.yaml, .github/workflows/release-python.yaml, .github/workflows/reusable-python-build-and-test.yaml, data-plane/python/integrations/slima2a/pyproject.toml, data-plane/python/integrations/slimrpc/pyproject.toml
Fix CI jobs for slimrpc and slima2a.
=> ci: fix slimrpc and slima2a working directory

data-plane/.release-plz.toml
Release the SRPC compiler plugin.
=> feat: srpc-compiler release

data-plane/.release-plz.toml, data-plane/srpc-compiler/Cargo.toml, data-plane/srpc-compiler/README.md
Readme to explain how to build and use the srpc compiler.
=> doc(srpc-compiler): add readme

.github/workflows/pr.yaml
Make sure the title of PRs respects the
[Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)
=> ci: add PR title check

data-plane/python/integrations/slimrpc/README.md, data-plane/python/integrations/slimrpc/README_pypi.md
Update SRPC README to reflect the latest changes in the library
Ref: #699
=> docs: update SRPC README

data-plane/python/bindings/examples/pyproject.toml
Upgrade example dependency to slim bindings 0.5.0
=> feat(python/bindings/examples): upgrade dep to slim 0.5.0

.github/release-config.json, .github/release-manifest.json
Fox release please path for python examples.
=> ci: fix python examples path

data-plane/core/service/src/service.rs, data-plane/core/service/src/session/handle.rs, data-plane/core/service/src/session/multicast.rs, data-plane/core/service/src/session/session_layer.rs, data-plane/python/bindings/examples/src/slim_bindings_examples/multicast.py, data-plane/python/bindings/src/pysession.rs, data-plane/python/bindings/tests/test_multicast.py, data-plane/testing/src/bin/channel.rs, data-plane/testing/src/bin/test_group.rs
=> feat(multicast): remove moderator parameter from configuration
